services:
  api:
    build:
      context: .
      target: development
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG}
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - SECRETS_FILE=/run/secrets/secrets.json
    secrets:
      - secrets.json
    deploy:
      resources:
        limits:
          cpus: '4'
secrets:
  secrets.json:
    file: secrets.json