definitions:
  repo.User:
    properties:
      accountStatus:
        type: string
      createdAt:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      fullName:
        type: string
      gender:
        type: string
      id:
        type: integer
      imageUrl:
        type: string
      isVerified:
        type: boolean
      phoneNumber:
        type: string
      role:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Home page.
      responses:
        "200":
          description: home page
          schema:
            type: html
      summary: Home Page
  /_:
    get:
      description: Admin route.
      responses:
        "200":
          description: Admin page
          schema:
            type: string
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Admin route
  /config:
    get:
      description: Get client config.
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get config
  /me:
    get:
      description: Get user.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repo.User'
        "401":
          description: invalid session
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get user
swagger: "2.0"
